// This file is @generated by prost-build.
/// ===== Request / Response Metadata =====
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestMeta {
    #[prost(string, tag = "1")]
    pub route: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub timestamp_ns: i64,
    /// original request body bytes (JSON)
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// ===== Request Payloads =====
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub meta: ::core::option::Option<RequestMeta>,
    #[prost(oneof = "request::Payload", tags = "10, 11, 20, 21")]
    pub payload: ::core::option::Option<request::Payload>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Single(super::SingleRequest),
        #[prost(message, tag = "11")]
        Batch(super::BatchRequest),
        #[prost(message, tag = "20")]
        CbAdd(super::CbAddRequest),
        #[prost(message, tag = "21")]
        CbRemove(super::CbRemoveRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleRequest {
    /// JSON-encoded request body
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchRequest {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<BatchItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchItem {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// JSON-encoded item body
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Continuous Batching
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CbAddRequest {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<RequestMeta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CbRemoveRequest {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
}
/// ===== Response Payloads =====
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "30")]
    pub metrics: ::core::option::Option<Metrics>,
    #[prost(oneof = "response::Payload", tags = "10, 11, 20")]
    pub payload: ::core::option::Option<response::Payload>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Single(super::SingleResponse),
        #[prost(message, tag = "11")]
        Batch(super::BatchResponse),
        #[prost(message, tag = "20")]
        CbCompleted(super::CbCompletedResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleResponse {
    /// JSON-encoded response body
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<BatchItemResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchItemResponse {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub status: ::core::option::Option<Status>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CbCompletedResponse {
    #[prost(message, repeated, tag = "1")]
    pub sequences: ::prost::alloc::vec::Vec<CompletedSequence>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletedSequence {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// JSON-encoded output
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Status {
    /// "Ok" | "Error"
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Metrics {
    #[prost(float, tag = "1")]
    pub prefill_ms: f32,
    #[prost(float, tag = "2")]
    pub decode_ms: f32,
    #[prost(int32, tag = "3")]
    pub tokens_generated: i32,
}
