# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import liteserver_pb2 as liteserver__pb2


class LiteServerStub(object):
    """===== gRPC Service =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/liteserver.LiteServer/Infer',
                request_serializer=liteserver__pb2.InferRequest.SerializeToString,
                response_deserializer=liteserver__pb2.InferResponse.FromString,
                )
        self.BatchInfer = channel.unary_unary(
                '/liteserver.LiteServer/BatchInfer',
                request_serializer=liteserver__pb2.BatchInferRequest.SerializeToString,
                response_deserializer=liteserver__pb2.BatchInferResponse.FromString,
                )
        self.StreamInfer = channel.unary_stream(
                '/liteserver.LiteServer/StreamInfer',
                request_serializer=liteserver__pb2.StreamInferRequest.SerializeToString,
                response_deserializer=liteserver__pb2.StreamChunk.FromString,
                )
        self.BidiStream = channel.stream_stream(
                '/liteserver.LiteServer/BidiStream',
                request_serializer=liteserver__pb2.BidiChunk.SerializeToString,
                response_deserializer=liteserver__pb2.BidiChunk.FromString,
                )
        self.DecoupledInfer = channel.unary_stream(
                '/liteserver.LiteServer/DecoupledInfer',
                request_serializer=liteserver__pb2.DecoupledInferRequest.SerializeToString,
                response_deserializer=liteserver__pb2.DecoupledResponse.FromString,
                )


class LiteServerServicer(object):
    """===== gRPC Service =====
    """

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecoupledInfer(self, request, context):
        """P9-1 (蓝图 §4.4, D18): one request → worker pushes N async responses
        over a long-lived channel whose lifetime the model controls (returns
        before close). Reuses the ZMQ stream mechanism with StreamOpen.decoupled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiteServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=liteserver__pb2.InferRequest.FromString,
                    response_serializer=liteserver__pb2.InferResponse.SerializeToString,
            ),
            'BatchInfer': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInfer,
                    request_deserializer=liteserver__pb2.BatchInferRequest.FromString,
                    response_serializer=liteserver__pb2.BatchInferResponse.SerializeToString,
            ),
            'StreamInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=liteserver__pb2.StreamInferRequest.FromString,
                    response_serializer=liteserver__pb2.StreamChunk.SerializeToString,
            ),
            'BidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidiStream,
                    request_deserializer=liteserver__pb2.BidiChunk.FromString,
                    response_serializer=liteserver__pb2.BidiChunk.SerializeToString,
            ),
            'DecoupledInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.DecoupledInfer,
                    request_deserializer=liteserver__pb2.DecoupledInferRequest.FromString,
                    response_serializer=liteserver__pb2.DecoupledResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liteserver.LiteServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LiteServer(object):
    """===== gRPC Service =====
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.LiteServer/Infer',
            liteserver__pb2.InferRequest.SerializeToString,
            liteserver__pb2.InferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.LiteServer/BatchInfer',
            liteserver__pb2.BatchInferRequest.SerializeToString,
            liteserver__pb2.BatchInferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/liteserver.LiteServer/StreamInfer',
            liteserver__pb2.StreamInferRequest.SerializeToString,
            liteserver__pb2.StreamChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/liteserver.LiteServer/BidiStream',
            liteserver__pb2.BidiChunk.SerializeToString,
            liteserver__pb2.BidiChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecoupledInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/liteserver.LiteServer/DecoupledInfer',
            liteserver__pb2.DecoupledInferRequest.SerializeToString,
            liteserver__pb2.DecoupledResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AdminStub(object):
    """===== Admin Service (P6, 蓝图 §4.1) =====

    18 RPCs mirroring the HTTP admin REST surface. Additive ONLY: a new service
    and new messages; no existing message/field is touched (proto 双用途 gRPC+ZMQ，
    additive 对 ZMQ wire 向后安全). gRPC reflection (评审低#12) 已实现：opt-in
    配置 `grpc.reflection: true`（默认关），见 src/grpc/reflection.rs。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/liteserver.Admin/GetInfo',
                request_serializer=liteserver__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=liteserver__pb2.GetInfoResponse.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/liteserver.Admin/ListModels',
                request_serializer=liteserver__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ListModelsResponse.FromString,
                )
        self.ListVersions = channel.unary_unary(
                '/liteserver.Admin/ListVersions',
                request_serializer=liteserver__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ListVersionsResponse.FromString,
                )
        self.ModelReady = channel.unary_unary(
                '/liteserver.Admin/ModelReady',
                request_serializer=liteserver__pb2.ModelReadyRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ModelReadyResponse.FromString,
                )
        self.ModelHealth = channel.unary_unary(
                '/liteserver.Admin/ModelHealth',
                request_serializer=liteserver__pb2.ModelHealthRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ModelHealthResponse.FromString,
                )
        self.LoadModel = channel.unary_unary(
                '/liteserver.Admin/LoadModel',
                request_serializer=liteserver__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=liteserver__pb2.LoadModelResponse.FromString,
                )
        self.UnloadModel = channel.unary_unary(
                '/liteserver.Admin/UnloadModel',
                request_serializer=liteserver__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=liteserver__pb2.UnloadModelResponse.FromString,
                )
        self.ReloadModel = channel.unary_unary(
                '/liteserver.Admin/ReloadModel',
                request_serializer=liteserver__pb2.ReloadModelRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ReloadModelResponse.FromString,
                )
        self.ActivateVersion = channel.unary_unary(
                '/liteserver.Admin/ActivateVersion',
                request_serializer=liteserver__pb2.ActivateVersionRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ActivateVersionResponse.FromString,
                )
        self.SetRouting = channel.unary_unary(
                '/liteserver.Admin/SetRouting',
                request_serializer=liteserver__pb2.SetRoutingRequest.SerializeToString,
                response_deserializer=liteserver__pb2.SetRoutingResponse.FromString,
                )
        self.GetModelStats = channel.unary_unary(
                '/liteserver.Admin/GetModelStats',
                request_serializer=liteserver__pb2.GetModelStatsRequest.SerializeToString,
                response_deserializer=liteserver__pb2.GetModelStatsResponse.FromString,
                )
        self.DeleteVersion = channel.unary_unary(
                '/liteserver.Admin/DeleteVersion',
                request_serializer=liteserver__pb2.DeleteVersionRequest.SerializeToString,
                response_deserializer=liteserver__pb2.DeleteVersionResponse.FromString,
                )
        self.DeleteModel = channel.unary_unary(
                '/liteserver.Admin/DeleteModel',
                request_serializer=liteserver__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=liteserver__pb2.DeleteModelResponse.FromString,
                )
        self.DeleteVersions = channel.unary_unary(
                '/liteserver.Admin/DeleteVersions',
                request_serializer=liteserver__pb2.DeleteVersionsRequest.SerializeToString,
                response_deserializer=liteserver__pb2.DeleteVersionsResponse.FromString,
                )
        self.RepositoryDrift = channel.unary_unary(
                '/liteserver.Admin/RepositoryDrift',
                request_serializer=liteserver__pb2.RepositoryDriftRequest.SerializeToString,
                response_deserializer=liteserver__pb2.RepositoryDriftResponse.FromString,
                )
        self.UploadModel = channel.stream_unary(
                '/liteserver.Admin/UploadModel',
                request_serializer=liteserver__pb2.UploadModelRequest.SerializeToString,
                response_deserializer=liteserver__pb2.UploadModelResponse.FromString,
                )
        self.DownloadModel = channel.unary_stream(
                '/liteserver.Admin/DownloadModel',
                request_serializer=liteserver__pb2.DownloadModelRequest.SerializeToString,
                response_deserializer=liteserver__pb2.DownloadModelChunk.FromString,
                )
        self.ListFiles = channel.unary_unary(
                '/liteserver.Admin/ListFiles',
                request_serializer=liteserver__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=liteserver__pb2.ListFilesResponse.FromString,
                )
        self.GetModelConfig = channel.unary_unary(
                '/liteserver.Admin/GetModelConfig',
                request_serializer=liteserver__pb2.GetModelConfigRequest.SerializeToString,
                response_deserializer=liteserver__pb2.GetModelConfigResponse.FromString,
                )


class AdminServicer(object):
    """===== Admin Service (P6, 蓝图 §4.1) =====

    18 RPCs mirroring the HTTP admin REST surface. Additive ONLY: a new service
    and new messages; no existing message/field is touched (proto 双用途 gRPC+ZMQ，
    additive 对 ZMQ wire 向后安全). gRPC reflection (评审低#12) 已实现：opt-in
    配置 `grpc.reflection: true`（默认关），见 src/grpc/reflection.rs。
    """

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRouting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVersion(self, request, context):
        """Repository lifecycle (model-upload-and-retire plan: G3 + E5 + F3) —
        delete/drift parity with the HTTP endpoints of the same name, plus
        file transfer RPCs. Additive-only, same as the P6 block above.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RepositoryDrift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelConfig(self, request, context):
        """M1 (admin-enhancement plan): model version config read — mirrors
        GET /v2/models/:m/versions/:v/config. Additive-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=liteserver__pb2.GetInfoRequest.FromString,
                    response_serializer=liteserver__pb2.GetInfoResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=liteserver__pb2.ListModelsRequest.FromString,
                    response_serializer=liteserver__pb2.ListModelsResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=liteserver__pb2.ListVersionsRequest.FromString,
                    response_serializer=liteserver__pb2.ListVersionsResponse.SerializeToString,
            ),
            'ModelReady': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelReady,
                    request_deserializer=liteserver__pb2.ModelReadyRequest.FromString,
                    response_serializer=liteserver__pb2.ModelReadyResponse.SerializeToString,
            ),
            'ModelHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelHealth,
                    request_deserializer=liteserver__pb2.ModelHealthRequest.FromString,
                    response_serializer=liteserver__pb2.ModelHealthResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=liteserver__pb2.LoadModelRequest.FromString,
                    response_serializer=liteserver__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=liteserver__pb2.UnloadModelRequest.FromString,
                    response_serializer=liteserver__pb2.UnloadModelResponse.SerializeToString,
            ),
            'ReloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadModel,
                    request_deserializer=liteserver__pb2.ReloadModelRequest.FromString,
                    response_serializer=liteserver__pb2.ReloadModelResponse.SerializeToString,
            ),
            'ActivateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateVersion,
                    request_deserializer=liteserver__pb2.ActivateVersionRequest.FromString,
                    response_serializer=liteserver__pb2.ActivateVersionResponse.SerializeToString,
            ),
            'SetRouting': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRouting,
                    request_deserializer=liteserver__pb2.SetRoutingRequest.FromString,
                    response_serializer=liteserver__pb2.SetRoutingResponse.SerializeToString,
            ),
            'GetModelStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStats,
                    request_deserializer=liteserver__pb2.GetModelStatsRequest.FromString,
                    response_serializer=liteserver__pb2.GetModelStatsResponse.SerializeToString,
            ),
            'DeleteVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVersion,
                    request_deserializer=liteserver__pb2.DeleteVersionRequest.FromString,
                    response_serializer=liteserver__pb2.DeleteVersionResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=liteserver__pb2.DeleteModelRequest.FromString,
                    response_serializer=liteserver__pb2.DeleteModelResponse.SerializeToString,
            ),
            'DeleteVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVersions,
                    request_deserializer=liteserver__pb2.DeleteVersionsRequest.FromString,
                    response_serializer=liteserver__pb2.DeleteVersionsResponse.SerializeToString,
            ),
            'RepositoryDrift': grpc.unary_unary_rpc_method_handler(
                    servicer.RepositoryDrift,
                    request_deserializer=liteserver__pb2.RepositoryDriftRequest.FromString,
                    response_serializer=liteserver__pb2.RepositoryDriftResponse.SerializeToString,
            ),
            'UploadModel': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=liteserver__pb2.UploadModelRequest.FromString,
                    response_serializer=liteserver__pb2.UploadModelResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=liteserver__pb2.DownloadModelRequest.FromString,
                    response_serializer=liteserver__pb2.DownloadModelChunk.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=liteserver__pb2.ListFilesRequest.FromString,
                    response_serializer=liteserver__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelConfig,
                    request_deserializer=liteserver__pb2.GetModelConfigRequest.FromString,
                    response_serializer=liteserver__pb2.GetModelConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liteserver.Admin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Admin(object):
    """===== Admin Service (P6, 蓝图 §4.1) =====

    18 RPCs mirroring the HTTP admin REST surface. Additive ONLY: a new service
    and new messages; no existing message/field is touched (proto 双用途 gRPC+ZMQ，
    additive 对 ZMQ wire 向后安全). gRPC reflection (评审低#12) 已实现：opt-in
    配置 `grpc.reflection: true`（默认关），见 src/grpc/reflection.rs。
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/GetInfo',
            liteserver__pb2.GetInfoRequest.SerializeToString,
            liteserver__pb2.GetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ListModels',
            liteserver__pb2.ListModelsRequest.SerializeToString,
            liteserver__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ListVersions',
            liteserver__pb2.ListVersionsRequest.SerializeToString,
            liteserver__pb2.ListVersionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModelReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ModelReady',
            liteserver__pb2.ModelReadyRequest.SerializeToString,
            liteserver__pb2.ModelReadyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModelHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ModelHealth',
            liteserver__pb2.ModelHealthRequest.SerializeToString,
            liteserver__pb2.ModelHealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/LoadModel',
            liteserver__pb2.LoadModelRequest.SerializeToString,
            liteserver__pb2.LoadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/UnloadModel',
            liteserver__pb2.UnloadModelRequest.SerializeToString,
            liteserver__pb2.UnloadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ReloadModel',
            liteserver__pb2.ReloadModelRequest.SerializeToString,
            liteserver__pb2.ReloadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActivateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ActivateVersion',
            liteserver__pb2.ActivateVersionRequest.SerializeToString,
            liteserver__pb2.ActivateVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRouting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/SetRouting',
            liteserver__pb2.SetRoutingRequest.SerializeToString,
            liteserver__pb2.SetRoutingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/GetModelStats',
            liteserver__pb2.GetModelStatsRequest.SerializeToString,
            liteserver__pb2.GetModelStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/DeleteVersion',
            liteserver__pb2.DeleteVersionRequest.SerializeToString,
            liteserver__pb2.DeleteVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/DeleteModel',
            liteserver__pb2.DeleteModelRequest.SerializeToString,
            liteserver__pb2.DeleteModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/DeleteVersions',
            liteserver__pb2.DeleteVersionsRequest.SerializeToString,
            liteserver__pb2.DeleteVersionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RepositoryDrift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/RepositoryDrift',
            liteserver__pb2.RepositoryDriftRequest.SerializeToString,
            liteserver__pb2.RepositoryDriftResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/liteserver.Admin/UploadModel',
            liteserver__pb2.UploadModelRequest.SerializeToString,
            liteserver__pb2.UploadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/liteserver.Admin/DownloadModel',
            liteserver__pb2.DownloadModelRequest.SerializeToString,
            liteserver__pb2.DownloadModelChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/ListFiles',
            liteserver__pb2.ListFilesRequest.SerializeToString,
            liteserver__pb2.ListFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/liteserver.Admin/GetModelConfig',
            liteserver__pb2.GetModelConfigRequest.SerializeToString,
            liteserver__pb2.GetModelConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
